Add support for serialising/deserialising enum elements
refractproject/minim pull request #138
Opened 2017-08-01 00:42 UTC by kylef

This adds support for enum element changes (https://github.com/apiaryio/api-elements/pull/28) in the JSON 0.6 serialiser.

2017-08-01 00:46 UTC, kylef commented on test/serialisers/json-0.6.js
> +    it('deserialises enum', function() {
Deserialising the 0.6 format into how the enum element works in API Elements 1.0.

2017-08-01 00:47 UTC, kylef commented on test/serialisers/json-0.6.js
> +    it('serialises enum', function() {
Serialising the API Elements 1.0 enum structure into the 0.6 format.

2017-08-01 00:47 UTC, kylef commented
This may well be missing something, should be verified with the Fury swagger adapter changes for enum element. @pksunkara can you take over this PR if it isn't correct so it can be completed before the end of our current sprint.

2017-08-01 01:03 UTC, pksunkara commented
Thomas is working on this. I didn't expect you to do this.

2017-08-01 20:35 UTC, pksunkara requested changes

2017-08-01 20:35 UTC, pksunkara commented on test/serialisers/json-0.6.js
> +      //console.log(JSON.stringify(minim.toRefract(enumeration), null, 2));
Can you delete this and extra empty line?

2017-08-01 20:35 UTC, pksunkara commented on test/serialisers/json-0.6.js
> +      //console.log(JSON.stringify(minim.toRefract(enumeration), null, 2));
Similarly here.

2017-08-01 20:35 UTC, pksunkara commented
And please check why the tests are failing.

2017-08-02 09:17 UTC, pksunkara approved these changes

2017-08-02 09:27 UTC, merged