feat: provide isMinim for ducktyping
refractproject/minim pull request #183
Opened 2018-07-23 16:25 UTC by opichals

Would help [here](https://github.com/refractproject/minim-api-description/issues/38) to create a generic `element` predicate while avoiding the use of the generally discouraged `instanceof` operator.

2018-07-23 16:53 UTC, opichals commented
Our current documentation workaround is to check `isFunction(element.toValue)` as we found the `isFunction(element.getMetaProperty)` fails for `ArraySlice`.

2018-07-23 18:01 UTC, honzajavorek commented
I don’t want to pick on words, but isn’t check on .toValue something one would call duck typing?

I mean, I thought duck typing is assuming something has certain behavior and if it doesn’t, then handle it differently/raise error.

Checking .isMinim sounds like an opposite. It doesn’t use instanceof, but it’s IMHO the same approach - type checking before I do something, only using a custom property unrelated to the behavior itself instead of inheritance built in the language.

2018-07-24 07:51 UTC, opichals commented
@honzajavorek Yes, perhaps checking the `toValue` is just enough and is what ducktyping is about.

For me it was about the likelihood of such a function to be present on the object which is subjectively higher to me than in the `isMinim`'s case.

2018-08-10 13:19 UTC, opichals commented
@kylef Could you please have a look?

2018-08-10 13:39 UTC, kylef commented
@opichals Can you please exlain why using `instanceof` is discouraged?

2018-08-10 14:06 UTC, opichals commented
@kylef I could mainly enumerate the following
* instanceof minim.Element doesn't work as the sole mini check (`minim.ArraySlice instanceof minim.Element === false`)
* when minim is bundled along with a library (e.g. attributes-kit) the instanceof checks fail when the minim.Element instances are created in the application scope

Also there is an explanation of the issue in the [minim predicates module README](https://github.com/apiaryio/documentation-service/blob/master/phoenix-ui/src/documentation/utils/minim/predicates/README.md#justification)

2018-08-10 19:22 UTC, kylef requested changes
@opichals Ok, I think it would make more sense to change the name, and also to differentiate between slice and element.

I don't want to couple the name of the library into its public API, in the future we intend for consumers to use [api-elements.js](https://github.com/apiaryio/api-elements.js) and they shouldn't have to know about implementation details like the underlying package is called minim etc. Having properties such as `isMinim` would expose these kinds of implementation details.

I think having `isElement` and `isElementSlice` properties would be clearer, and allow you to actually know if its an element or a slice.

2018-08-10 19:25 UTC, kylef commented
> When creating a new minim namespace the new types/classes are created in runtime and there is no way to statically use instanceof to assert the proper type. The predicates are only concerned by the shape of the elements not by an Is-a relations which is the tightest form of coupling and should be generally avoided.

@opichals I'd dispute that reasoning for minim to not use `instanceof`. Base element types are not created in runtime and thus it would be possible to use `instanceof`.

2018-08-29 06:30 UTC, opichals commented
> Base element types are not created in runtime and thus it would be possible to use instanceof.

/cc @char0n

2018-08-29 06:50 UTC, opichals commented
> I think having isElement and isElementSlice properties would be clearer, and allow you to actually know if its an element or a slice.

To me the `isElement` wording is rising the likelihood of a naming collision.

[Used instanceof in attributes-kit](https://github.com/apiaryio/attributes-kit/blob/master/src/Components/Attributes/Attributes.js#L27) so closing this.

2018-08-29 06:50 UTC, closed without merging